### ISSUE TITLE
Footer not displayed in some previews

### ISSUE THREAD

**Issue by stevenferey** [gdcc/dataverse-previewers#44]
Hello,

We observed a fault in the display of the footer which is visible in some previews.
For example, an [image](https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/XINVMQ/V6IT23&version=1.0) and a [pdf](https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/XINVMQ/PTUOYS) of the Dataverse demo portal : 

The content of the footer is not loaded, the name of the property is directly displayed, , linked to the code: 
https://github.com/gdcc/dataverse-previewers/blob/develop/previewers/v1.3/js/retriever.js#L191

![Capture d’écran du 2023-12-06 17-00-32](https://github.com/gdcc/dataverse-previewers/assets/13960773/ca46c947-761e-4f53-bf01-025dbef441f9)

If you explore the document in a separate browser tab, the footer is displayed correctly : 

![Capture d’écran du 2023-12-06 17-01-14](https://github.com/gdcc/dataverse-previewers/assets/13960773/132b27a8-5e55-4158-89b7-78365cffea0e)

This problem was observed on versions 5.12.1+ of Dataverse
Browsers tested: Firefox and Brave

Thanks

**Comment by qqmyers** [comment]
This appears to be fixed in v1.4 (I tested with Dataverse 6.1, but I don't think the Dataverse code should be involved in this.) I don't think there was a specific fix for this but the timing of when the i18n functionality was initialized changed which could be what's needed. If you still see this with v1.4, let us know.

**Comment by qqmyers** [comment]
Closing assuming v1.4 fixed this. If not, let us know.
